import json
import os
import re

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

LLM_MODEL = "llama-3.3-70b-versatile"


def analyze_llm(text: str) -> float:
    """Signal 1: LLM semantic classifier. Returns 0.0 (human) to 1.0 (AI)."""
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    prompt = (
        "Analyze the following text and determine whether it was likely written by a "
        "human or generated by AI.\n\n"
        f'Text:\n"""\n{text}\n"""\n\n'
        "Respond with ONLY a JSON object: "
        '{"ai_probability": <float 0.0 to 1.0>, "reasoning": "<brief explanation>"}\n'
        "Where 0.0 = confident human-written, 1.0 = confident AI-generated."
    )
    response = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=200,
    )
    raw = response.choices[0].message.content.strip()
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        data = json.loads(match.group())
        return max(0.0, min(1.0, float(data["ai_probability"])))
    return 0.5


def _split_sentences(text: str) -> list[str]:
    parts = re.split(r"[.!?]+", text)
    return [s.strip() for s in parts if s.strip()]


def analyze_stylometric(text: str) -> float:
    """Signal 2: Stylometric heuristics. Returns 0.0 (human-like) to 1.0 (AI-like)."""
    words = re.findall(r"\b[a-zA-Z']+\b", text.lower())
    sentences = _split_sentences(text)

    if len(words) < 10 or len(sentences) < 2:
        return 0.5

    # Sentence length variance — AI tends toward uniform lengths
    lengths = [len(re.findall(r"\b\w+\b", s)) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    # Normalize: low variance (< 5) → AI-like (1.0), high variance (> 30) → human-like (0.0)
    variance_score = max(0.0, min(1.0, 1.0 - variance / 30.0))

    # Type-token ratio — unique words / total words
    ttr = len(set(words)) / len(words)
    # AI tends toward moderate TTR (~0.5-0.7); very high or very low can be human
    ttr_score = max(0.0, min(1.0, 1.0 - abs(ttr - 0.55) / 0.35))

    # Punctuation density — AI uses predictable punctuation patterns
    punct_count = len(re.findall(r"[,;:\-—()\"']", text))
    punct_density = punct_count / len(sentences)
    # Moderate density (~1-3 per sentence) → AI-like
    punct_score = max(0.0, min(1.0, 1.0 - abs(punct_density - 2.0) / 3.0))

    return round((variance_score + ttr_score + punct_score) / 3, 4)
